//
//  AlbumsInteractor.swift
//  MyLovcen
//
//  Created by Andrija Scepanovic on 9/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class AlbumsInteractor {

    // MARK: Private Properties

    private let service: APIService
    private let sessionManager: SessionManager

    init(
        service: APIService = APIService.instance,
        sessionManager: SessionManager = .default
    ) {
        self.service = service
        self.sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension AlbumsInteractor: AlbumsInteractorInterface {

    func fetchAlbums() -> Single<[Album]> {
        return service.rx
            .request(
                [Album].self,
                router: AlbumRouter.get(),
                session: sessionManager.session
            )
    }

}
