//
//  AlbumsWireframe.swift
//  MyLovcen
//
//  Created by Andrija Scepanovic on 9/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class AlbumsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Albums", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: AlbumsViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = AlbumsInteractor()
        let presenter = AlbumsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension AlbumsWireframe: AlbumsWireframeInterface {

    func showPhotos(for albumId: Int) {
        navigationController?.pushWireframe(PhotosWireframe(albumId: albumId))
    }
}
