//
//  AlbumsInterfaces.swift
//  MyLovcen
//
//  Created by Andrija Scepanovic on 9/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol AlbumsWireframeInterface: WireframeInterface {
    func showPhotos(for albumId: Int)
}

protocol AlbumsViewInterface: ViewInterface, Refreshable, Progressable {
}

protocol AlbumsPresenterInterface: PresenterInterface {
    func configure(with output: Albums.ViewOutput) -> Albums.ViewInput
}

protocol AlbumsInteractorInterface: InteractorInterface {
    func fetchAlbums() -> Single<[Album]>
}

enum Albums {

    struct ViewOutput {
        let pullToRefresh: Signal<Void>
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }

}
