//
//  PhotosWireframe.swift
//  PinchAssignment
//
//  Created by Andrija Scepanovic on 9/30/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class PhotosWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Photos", bundle: nil)

    // MARK: - Module setup -

    init(albumId: Int) {
        let moduleViewController = storyboard.instantiateViewController(ofType: PhotosViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = PhotosInteractor(albumId: albumId)
        let presenter = PhotosPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PhotosWireframe: PhotosWireframeInterface {
}
