//
//  PhotosViewController.swift
//  PinchAssignment
//
//  Created by Andrija Scepanovic on 9/30/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class PhotosViewController: UIViewController {

    // MARK: - IB Outlets -

    @IBOutlet weak var tableView: UITableView! {
        didSet {
            tableView.registerNib(cellOfType: PhotoTableViewCell.self)
            tableView.tableFooterView = UIView()
        }
    }

    // MARK: - Public properties -

    var presenter: PhotosPresenterInterface!

    lazy var refreshControl: UIRefreshControl = {
        let refreshControl = UIRefreshControl()
        tableView.refreshControl = refreshControl
        return refreshControl
    }()

    // MARK: - Private properties -

    private lazy var tableDataSourceDelegate: TableDataSourceDelegate = {
        TableDataSourceDelegate(tableView: tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension PhotosViewController: PhotosViewInterface {
}

private extension PhotosViewController {

    func setupView() {
        let pullToRefresh = refreshControl.rx
            .controlEvent(.valueChanged)
            .asSignal()
            .mapToVoid()

        let willDisplayLastCell = tableView.rx.reachedBottomOnceWith(restart: pullToRefresh.asDriverOnErrorComplete())

        let output = Photos.ViewOutput(pullToRefresh: pullToRefresh, willDisplayLastCell: willDisplayLastCell)

        let input = presenter.configure(with: output)

        input.items
            .drive(tableDataSourceDelegate.rx.items)
            .disposed(by: disposeBag)
    }

}
