//
//  PhotosInterfaces.swift
//  MyLovcen
//
//  Created by Andrija Scepanovic on 9/30/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol PhotosWireframeInterface: WireframeInterface {
}

protocol PhotosViewInterface: ViewInterface, Progressable, Refreshable {
}

protocol PhotosPresenterInterface: PresenterInterface {
    func configure(with output: Photos.ViewOutput) -> Photos.ViewInput
}

protocol PhotosInteractorInterface: InteractorInterface {
    func fetchPhotos(loadNextPage: Driver<Void>, reload: Driver<Void>) -> Observable<[PhotoModel]>
}

enum Photos {

    struct ViewOutput {
        let pullToRefresh: Signal<Void>
        let willDisplayLastCell: Driver<Void>
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }

}
